//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.19455
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApiMovie.Translator {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApiMovie.Translator.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://datamarket.accesscontrol.windows.net/v2/OAuth2-13.
        /// </summary>
        internal static string DatamarketAccessUri {
            get {
                return ResourceManager.GetString("DatamarketAccessUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.microsofttranslator.com/v2/Http.svc/Translate?text={0}&amp;from={1}&amp;to={2}.
        /// </summary>
        internal static string TranslatorURI {
            get {
                return ResourceManager.GetString("TranslatorURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 53f3d1c4-bfbc-4612-bb1f-cdf3d3167b7a.
        /// </summary>
        internal static string TranslatorUserId {
            get {
                return ResourceManager.GetString("TranslatorUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YnEefbyKCLu/r/Bf+femxjoEYgGHBpzNGOkPqtzSnLc.
        /// </summary>
        internal static string TranslatorUserKey {
            get {
                return ResourceManager.GetString("TranslatorUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grant_type=client_credentials&amp;client_id={0}&amp;client_secret={1}&amp;scope=http://api.microsofttranslator.com.
        /// </summary>
        internal static string UriClientCredentials {
            get {
                return ResourceManager.GetString("UriClientCredentials", resourceCulture);
            }
        }
    }
}
