//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.19455
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApiMovie.TheMovieDb.TheMovieDb {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheMovieDbImage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheMovieDbImage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApiMovie.TheMovieDb.TheMovieDb.TheMovieDbImage", typeof(TheMovieDbImage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://image.tmdb.org/t/p/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a h632.
        /// </summary>
        internal static string h632 {
            get {
                return ResourceManager.GetString("h632", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a original.
        /// </summary>
        internal static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://image.tmdb.org/t/p/.
        /// </summary>
        internal static string SecureBaseUrl {
            get {
                return ResourceManager.GetString("SecureBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w1280.
        /// </summary>
        internal static string W1280 {
            get {
                return ResourceManager.GetString("W1280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w154.
        /// </summary>
        internal static string w154 {
            get {
                return ResourceManager.GetString("w154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w185.
        /// </summary>
        internal static string w185 {
            get {
                return ResourceManager.GetString("w185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w300.
        /// </summary>
        internal static string w300 {
            get {
                return ResourceManager.GetString("w300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w342.
        /// </summary>
        internal static string w342 {
            get {
                return ResourceManager.GetString("w342", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w45.
        /// </summary>
        internal static string w45 {
            get {
                return ResourceManager.GetString("w45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w500.
        /// </summary>
        internal static string w500 {
            get {
                return ResourceManager.GetString("w500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w780.
        /// </summary>
        internal static string w780 {
            get {
                return ResourceManager.GetString("w780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a w92.
        /// </summary>
        internal static string w92 {
            get {
                return ResourceManager.GetString("w92", resourceCulture);
            }
        }
    }
}
